service: consumer-user-api
frameworkVersion: '2'

provider:
  name: aws
  region: us-east-1
  runtime: python3.8
  lambdaHashingVersion: 20201221
  iamRoleStatements:
      - Effect: Allow
        Action:
          - rds-data:ExecuteSql
          - rds-data:ExecuteStatement
        Resource: "MY_CLUSTER_ARN"
      - Effect: Allow
        Action:
          - secretsmanager:GetSecretValue
          - secretsmanager:PutResourcePolicy
          - secretsmanager:PutSecretValue
          - secretsmanager:DeleteSecret
          - secretsmanager:DescribeSecret
          - secretsmanager:TagResource
        Resource: "*"


functions:
  post:
    handler: scripts/post.post
    events:
      - http:
          path: /new-user
          method: POST
  get:
    handler: scripts/get.get
    events:
      - http:
          path: /new-user/{id}
          method: GET
  reset-passwword:
    handler: scripts/resetPassword.resetPassword
    events:
      - http:
          path: /reset-passwword
          method: POST