service: cart-api
frameworkVersion: '2'

provider:
  name: aws
  region: us-east-1
  runtime: python3.8
  lambdaHashingVersion: '20201221'
  iamRoleStatements:
      - Effect: Allow
        Action:
          - rds-data:ExecuteSql
          - rds-data:ExecuteStatement
        Resource: "MY_CLUSTER_ARN "
      - Effect: Allow
        Action:
          - secretsmanager:GetSecretValue
          - secretsmanager:PutResourcePolicy
          - secretsmanager:PutSecretValue
          - secretsmanager:DeleteSecret
          - secretsmanager:DescribeSecret
          - secretsmanager:TagResource
        Resource: "*"


functions:
  get-chart:
    handler: scripts/getCart.getCart
    events:
      - http:
          path: /get-cart/{username}
          method: GET
  add-to-chart:
    handler: scripts/addToCart.addToCart
    events:
      - http:
          path: /add-to-cart
          method: POST
  delete-from-chart:
    handler: scripts/deleteFromCart.deleteFromCart
    events:
      - http:
          path: /delete-from-cart
          method: POST
  checkout:
    handler: scripts/checkout.checkout
    events:
      - http:
          path: /checkout
          method: GET